import type { EmailKind, EmailPayloads } from "./templates.js";

/** One sample payload per kind — the test that every template renders, has
 *  a subject, carries the logo and never leaks raw HTML from user data. */
export const SAMPLES: { [K in EmailKind]: EmailPayloads[K] } = {
  welcome: { displayName: "Ada Lovelace" },
  workspace_created: { displayName: "Ada Lovelace", orgName: "Riverbend Youth Center", orgSlug: "riverbend" },
  added_to_workspace: { displayName: "Grace Hopper", orgName: "Riverbend Youth Center", role: "admin", addedBy: "Ada Lovelace" },
  password_reset: { displayName: "Ada Lovelace", resetUrl: "https://deedwell.org/reset-password?token=abc", expiresMinutes: 60 },
  password_changed: { displayName: "Ada Lovelace", sessionsRevoked: true },
  temp_password: { displayName: "Grace Hopper", tempPassword: "k9Qm-2pLx7Vw", orgName: "Riverbend Youth Center", reason: "created" },
  support_received: { displayName: "Ada Lovelace", orgName: "Riverbend Youth Center", body: "Our logo upload keeps failing <script>alert(1)</script>" },
  support_reply: { displayName: "Ada Lovelace", orgName: "Riverbend Youth Center", body: "Fixed — try again and let us know." },
  topup_receipt: { orgName: "Riverbend Youth Center", packageName: "Standard", tokens: 5_000_000, amountCents: 4000, currency: "usd", transactionId: "0192a1b2-c3d4-7e5f-8a9b-0c1d2e3f4a5b", resumedRuns: 2, purchasedBy: "Ada Lovelace" },
  out_of_tokens: { orgName: "Riverbend Youth Center", what: "Launch the Riverbend website" },
  low_balance: { orgName: "Riverbend Youth Center", tokenBalance: 180_000 },
  billing_exempt: { orgName: "Riverbend Youth Center" },
  site_preview_ready: { orgName: "Riverbend Youth Center", siteName: "Riverbend Youth Center", version: 3, previewUrl: "https://preview-riverbend.deedwell.org", warnings: ["Missing alt text (about): 2 images"] },
  site_build_failed: { orgName: "Riverbend Youth Center", siteName: "Riverbend Youth Center", version: 3, previewUrl: "https://preview-riverbend.deedwell.org", blocking: ["Broken link (home): /donate", "Placeholder text (about): [ADD MISSION]"] },
  site_published: { orgName: "Riverbend Youth Center", siteName: "Riverbend Youth Center", liveUrl: "https://riverbend.deedwell.org", partnerBuilt: false },
  run_failed: { orgName: "Riverbend Youth Center", title: "Get approved for Google Ad Grants", error: "Google returned 503 three times", status: "failed" },
  approval_needed: { orgName: "Riverbend Youth Center", title: "Apply for the Community Foundation grant", agentName: "David", nextAction: "review and approve the bid decision" },
  info_needed: { orgName: "Riverbend Youth Center", title: "Apply for the Community Foundation grant", agentName: "Naomi", nextAction: "provide EIN, annual budget and 1 more" },
  grant_package_ready: { orgName: "Riverbend Youth Center", opportunityTitle: "Youth Literacy Initiative", funder: "Community Foundation of Atlanta" },
  content_campaign_finished: { orgName: "Riverbend Youth Center", title: "Spring fundraising drive", status: "ready" },
  post_failed: { orgName: "Riverbend Youth Center", platform: "Facebook", accountName: "Riverbend Youth Center", scheduledAt: "2026-09-08T14:00:00Z", error: "The connection expired and needs to be reconnected.", content: "Join us Saturday for the river clean-up! 🌊" },
  connector_attention: { orgName: "Riverbend Youth Center", provider: "Instagram", accountName: "@riverbendyouth", detail: "The connection expired and needs to be reconnected." },
  form_submission: { orgName: "Riverbend Youth Center", siteName: "Riverbend Youth Center", formKey: "contact", fields: [["name", "Jordan Lee"], ["email", "jordan@example.org"], ["message", "I'd like to volunteer on weekends."]] },
  ad_grants_review: { orgName: "Riverbend Youth Center", status: "approved", reason: null },
  ad_grants_reconnect: { orgName: "Riverbend Youth Center", step: "submit_activation" },
  ad_grants_live: { orgName: "Riverbend Youth Center", campaignId: "1234567890" },
  google_ads_connected: { orgName: "Riverbend Youth Center", accountName: "Riverbend Youth Center Ads", customerId: "123-456-7890" },
  google_ads_published: { orgName: "Riverbend Youth Center", campaignName: "Riverbend — After-school programs", adCount: 4, paused: true },
  ad_grants_email: { orgName: "Riverbend Youth Center", from: "Google for Nonprofits <nonprofits-noreply@google.com>", subject: "Action required: verify your organization", verdict: "Action needed", excerpt: "To complete your request, please upload a copy of your IRS determination letter within 14 days." },
  task_approval_requested: { orgName: "Riverbend Youth Center", taskTitle: "Weekly donor thank-you notes", agentName: "Maya" },
  task_completed: { orgName: "Riverbend Youth Center", taskTitle: "Weekly donor thank-you notes", agentName: "Maya", summary: "Drafted 12 thank-you notes and a summary sheet.", deliverables: ["Thank-you notes (12)", "Donor summary.csv"], runNumber: 4, nextRunAt: "2026-09-14T13:00:00Z" },
  task_failed: { orgName: "Riverbend Youth Center", taskTitle: "Weekly donor thank-you notes", agentName: "Maya", error: "The donor spreadsheet could not be read." },
  task_needs_input: { orgName: "Riverbend Youth Center", taskTitle: "Weekly donor thank-you notes", agentName: "Maya", question: "Should I include the donors who gave anonymously?" },
  teammate_message: { orgName: "Riverbend Youth Center", agentName: "Maya", agentRole: "Executive Assistant", message: "The grant deadline is Friday — want me to schedule the final review?" },
  unread_digest: { orgName: "Riverbend Youth Center", displayName: "Ada Lovelace", total: 5, channels: [{ name: "Maya", count: 3 }, { name: "Website project", count: 2 }] },
  ops_alert: { title: "New signup", rows: [["Name", "Ada Lovelace"], ["Email", "ada@example.org"]], tone: "ok" },
};
